version: '3.8'

services:
    db:
        image: mysql:8.0
        container_name: mysql_container
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: rootpassword
            MYSQL_DATABASE: mydatabase
            MYSQL_USER: user
            MYSQL_PASSWORD: userpassword
        ports:
            - "3306:3306"
        volumes:
            - db_data:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin_container
        restart: always
        environment:
            PMA_HOST: db
            MYSQL_ROOT_PASSWORD: rootpassword
        ports:
            - "8080:80"

volumes:
    db_data:
